# Generated by Django 4.1.4 on 2022-12-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Счёт игрока в игре!'),
        ),
    ]
