# Generated by Django 4.1.4 on 2022-12-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=1, verbose_name='Счёт игрока в игре!'),
        ),
    ]
