# Generated by Django 4.1.4 on 2022-12-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_link',
            field=models.IntegerField(default=0, verbose_name='Переходы по ссылке'),
        ),
    ]
